Macos support.
Chicken-Bones/FactorioAchievementPlaytimePatcher pull request #3
Opened 2024-12-11 08:53 UTC by covers1624

Tasks:
- [x] Support for macos.
- [x] Unify all patching paths.
- [ ] Strip Macos signing information.

2024-12-13 01:21 UTC, Chicken-Bones commented on Program.cs
> -	Console.Error.WriteLine(ex.Message);
This was intentional. Otherwise there's no point separating out `ArgumentException`. I used it to provide user facing error messages

2024-12-13 01:21 UTC, Chicken-Bones commented on Patches.cs
> +		public static Dictionary<OSPlatform, Dictionary<Architecture, Patch[]>> PlatformPatchSets = new() {
Do you need to expose each of the `<Platform>PatchSets` dicts above? I think it looks better to create them inline in this nested dictionary here.

2025-03-13 10:48 UTC, covers1624 commented on Patches.cs
> +		public static Dictionary<OSPlatform, Dictionary<Architecture, Patch[]>> PlatformPatchSets = new() {
Fixed, Merged all the dicts together.

2025-03-13 10:48 UTC, covers1624 commented on Program.cs
> -	Console.Error.WriteLine(ex.Message);
Don't think I intended to commit this. Reverted.

2025-03-14 00:14 UTC, Chicken-Bones requested changes
Looks great, just code style change requests

2025-03-14 00:14 UTC, Chicken-Bones commented on Program.cs
> +		throw new ArgumentException($"Usage: <path to factorio.exe or map.zip> [<path to output>]");
`map.zip` approach got abandoned

2025-03-14 00:14 UTC, Chicken-Bones commented on AssemblyProvider.cs
> +            Console.WriteLine("         \"codesign\" form the Xcode command line tools, or Quill(https://github.com/anchore/quill)");
`form` -> `from`

2025-03-14 00:14 UTC, Chicken-Bones commented on AssemblyProvider.cs
> +            Console.WriteLine("         is required to be available on PATH to patch macOS binaries.");
remove `to be available`

2025-03-14 00:14 UTC, Chicken-Bones commented on AssemblyProvider.cs
> +                UseShellExecute = false,
this is the default value

2025-03-14 00:14 UTC, Chicken-Bones commented on AssemblyProvider.cs
> +            RedirectStandardOutput = false,
These are the default values

2025-03-14 00:14 UTC, Chicken-Bones commented on AssemblyProvider.cs
> +    public bool PreCheck() {
Can we just throw an exception from `FindSignerProgram` instead of having a separate `PreCheck`? It can be of another type which only shows message and not stack trace in the top level catch. Also means `_signer` is no longer nullable

2025-03-14 00:14 UTC, Chicken-Bones commented on AssemblyProvider.cs
> +    private Signer?                           _signer;
haha, I won't make you change it, but this spacing is very non-standard

2025-03-14 00:14 UTC, Chicken-Bones commented on AssemblyProvider.cs
> +        if (MachOReader.TryLoadFat(new MemoryStream(moduleBytes), out var fat, false)) {
`fat` is not disposable here?

2025-03-15 05:05 UTC, covers1624 commented on AssemblyProvider.cs
> +        if (MachOReader.TryLoadFat(new MemoryStream(moduleBytes), out var fat, false)) {
Nope, MachOFat doesn't keep the stream open, or use any lazy loading.

2025-03-15 05:07 UTC, covers1624 commented on AssemblyProvider.cs
> +                UseShellExecute = false,
I blame tML for this, as I used it as reference for how to exec stuff :)

2025-03-15 05:08 UTC, covers1624 commented on AssemblyProvider.cs
> +    public bool PreCheck() {
Done.

2025-03-15 05:08 UTC, covers1624 commented on AssemblyProvider.cs
> +    private Signer?                           _signer;
Rider default formatting rules aligns things. Have disabled it and formatted the file.

2025-03-15 05:09 UTC, covers1624 commented on Program.cs
> +		throw new ArgumentException($"Usage: <path to factorio.exe or map.zip> [<path to output>]");
Nuked.

2025-03-15 05:09 UTC, covers1624 commented on AssemblyProvider.cs
> +            Console.WriteLine("         \"codesign\" form the Xcode command line tools, or Quill(https://github.com/anchore/quill)");
Fixed.

2025-03-15 05:09 UTC, covers1624 commented on AssemblyProvider.cs
> +            Console.WriteLine("         is required to be available on PATH to patch macOS binaries.");
Fixed.

2025-03-16 03:41 UTC, Chicken-Bones commented on Program.cs
> +	Console.WriteLine("         is required on PATH to patch macOS binaries.");
Could reduce coupling if this was the exception message, and we just print `ex.Message`, but doesn't really matter

2025-03-16 05:59 UTC, merged